# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다.

> **pytorch의 tensor는 숫자 데이터 타입만 지원한다.**

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
      
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [2]:
import torch

In [3]:
print('torch Data types')
print("float", torch.float16, torch.float32, torch.float64, torch.float, torch.double)  #torch.float: float32
print("int:", torch.int8, torch.int16, torch.int32, torch.int64)#  torch.short, torch.int, torch.long 가능
print("uint:", torch.uint8, torch.uint16, torch.uint32, torch.uint64)
print("bool:", torch.bool)

torch Data types
float torch.float16 torch.float32 torch.float64 torch.float32 torch.float64
int: torch.int8 torch.int16 torch.int32 torch.int64
uint: torch.uint8 torch.uint16 torch.uint32 torch.uint64
bool: torch.bool


In [ ]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)



print("shape:", a.shape, a.size())
print("0축 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)  # type(): Tensor 객체 타입. dtype: data type => 둘은 좀 다르다.
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device)  # tensor를 다루는 processor(메모리위치) - cpu, cuda(gpu)

shape: torch.Size([2, 2]) torch.Size([2, 2])
0축 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [7]:
aa = torch.tensor(range(10))
print(aa)
aa.type()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


'torch.LongTensor'

In [8]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
c = torch.IntTensor([10,20,30])    # int32
print(c.dtype)
d = torch.DoubleTensor([1, 2, 3])  # float64
print(d.dtype)
e = torch.LongTensor([10, 20, 30]) # int64
print(e.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


## 동일한 값을 원소로 가지는 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(size, fill_value), full_like(텐서, fill_value)**: 지정한 값으로 구성된 tensor생성
  - size 
    - shape을 지정한다.
    - zeros, ones는 가변인자이므로 축별 size를 순서대로 서정
    - full 은 tuple/list로 shape을 지정한다.
    

In [10]:
torch.zeros(3,2,3)  # 3 x 2 x 3
# a.dtype
torch.ones(2,3)  # 2 x 3
torch.full([3,2], fill_value=100)  #  3 x 2


tensor([[100, 100],
        [100, 100],
        [100, 100]])

In [13]:
# 특정 배열과 동일한 shape의 tensor 생성.
a = torch.tensor([[1, 2],[3, 4]]) # 2 x 2

print(a.shape)
b = torch.zeros_like(a)  # a와 같은 shape으로 생성.
b = torch.ones_like(a)
b = torch.full_like(a, 20)
print(b.shape, d.dtype)
b

torch.Size([2, 2])
torch.Size([2, 2]) torch.float64


tensor([[20, 20],
        [20, 20]])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [14]:
torch.arange(10)  # end. 0 ~ 10 1씩 증가
torch.arange(0, 1, 0.1) # 0 ~ 1, 0.1 
torch.arange(10, 1, -1) # 10 ~ 1, -1 

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
torch.linspace(0, 10, 5)  # 0 ~ 10 , 5개 원소
torch.linspace(0, 1, 11)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [16]:
torch.empty(3,2,7)

tensor([[[1.4678e-06, 1.4097e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [26]:
torch.manual_seed(0)  # seed 설정
torch.rand(100, 3, 5) #.shape
torch.randn(30,3)
torch.randint(1, 100, (3,3))  
torch.randperm(5) # 0 ~ 4 를 섞어서 구성

tensor([0, 4, 3, 2, 1])

In [18]:
a = torch.arange(100)
# a 섞기
idx = torch.randperm(100) # 0 ~ 99 섞어서 반환. -> index
a[idx]

tensor([ 2, 51,  4, 90, 27, 18,  6, 66, 79, 32, 72, 67, 33, 68, 30, 78, 65, 53,
        40, 63, 54, 77, 43, 24, 80, 83, 57, 98, 69, 56, 70,  7, 76, 31, 97, 89,
        38, 48, 11, 23,  0, 71, 25, 49, 62, 17, 88, 14, 73, 92, 20, 19, 52,  1,
        41, 58, 16, 12, 81, 75, 93, 74, 91,  5, 50, 39, 45, 35,  9, 10,  3, 46,
        21, 82, 36, 59, 96,  8, 87, 42, 64, 26, 34, 95, 85, 13, 86, 28, 61, 55,
        22, 99, 94, 44, 37, 47, 60, 15, 29, 84])

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [ ]:
import torch
# device = 'mps' if torch.backends.mps.is_available() else 'cpu'
# device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [ ]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device) # 생성할 때 device 지정.
print(t, t.device)  # tensor가 어느 device 에 있는지 확인.

tensor([1., 2., 3.]) cpu


In [ ]:
t2 = t.to("cpu")  # 다른 device로 옮기기.
print(t2, t2.device)

tensor([1., 2., 3.]) cpu


## tensor를 상수로 변환
- torch.Tensor객체를 파이썬 상수로 변환.
- tensor객체.item()
    - Scalar(상수) 또는 원소가 하나인 tensor를 python 상수로 변환

In [ ]:
print(torch.tensor(30))  # 학습에 필요한 다양한 값들을 갖고 있음.

tensor(30)


In [34]:
a = torch.tensor(10)  # 상수(scalar) => 0차원 Tensor
print(a, a.ndim)
print(a.item())
print(type(a), type(a.item()))

tensor(10) 0
10
<class 'torch.Tensor'> <class 'int'>


In [36]:
b = torch.tensor([[20]]) # 원소가 하나인 N차원 배열
print(b, b.dim())
print(b.item()) #원소가 하나인 배열(텐서) 변환 가능

tensor([[20]]) 2
20


In [39]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [ ]:
import numpy as np
import torch

# d = torch.tensor([10], device='cuda')
# print(d)
# print(d.item())

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [40]:
import numpy as np
import torch

In [41]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr, dtype=torch.float32)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.to("cpu").numpy()  # tensor를 cpu로 옮긴 다음에 numpy로 바꿔줌.

tensor([[ 1.2466, -0.1142, -0.2171],
        [-0.6646, -1.4025, -0.3587],
        [-3.6123,  0.1928,  0.6963]])


array([[ 1.2465531 , -0.11420384, -0.21706334],
       [-0.6645675 , -1.402465  , -0.35869935],
       [-3.6122813 ,  0.19283396,  0.6962579 ]], dtype=float32)

In [ ]:
t2 = torch.randn(2,2, device="cuda") 
t2

AssertionError: Torch not compiled with CUDA enabled

In [44]:
t2.numpy() 
# t2.to("cpu").numpy()

array([1., 2., 3.], dtype=float32)

# 원소 조회및 변경 - indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>**


In [ ]:
t = torch.randint(-10, 10, (100, ))  # 난수로 만들어줌.
t

tensor([-10,  -5, -10,  -3,  -8,  -8,   9,  -4,  -9,  -6,  -3,  -2,  -6,   1,
          5,   6,  -7, -10,   6,   2,   9,   5,  -1,  -6,  -2,  -2,  -1,  -6,
         -5,   3,   1,  -1,  -7,   8, -10,   0,   2,  -1,  -7,  -5, -10, -10,
         -9,  -2,  -6,  -8,  -1,  -4,  -1,   4,   1,  -6,   6,  -1,  -1,  -1,
         -8,  -1,  -2,  -9,  -2,   8,  -6,   9,   6,   1,  -4,   2,   0,   8,
          9,   0, -10,   9,   0,   7,   1,   2,   2,   7,   9,  -1,  -7,  -7,
          3,  -1,   5,  -4,   1,  -2, -10,  -5,  -7,   8,  -8,  -5,   3,   3,
          7,   0])

In [46]:
t[0]
t[[1, 5, -1]] # 여러개 조회-> fancy indexing

tensor([-5, -8,  0])

In [52]:
t[:5]
t[10:15]
t[90:]
t[3:30:3]


# t[10:1:-2]  # step 음수 안됨. reverse 안됨. reverse하려면 flip() 사용
t[1:10:2].flip(dims=(0,)) #reverse

tensor([-6, -4, -8, -3, -5])

# boolean index
- 논리 연산은 &, |, ~ 을 사용한다.

In [53]:
# boolean index
t[t > 0]

tensor([9, 1, 5, 6, 6, 2, 9, 5, 3, 1, 8, 2, 4, 1, 6, 8, 9, 6, 1, 2, 8, 9, 9, 7,
        1, 2, 2, 7, 9, 3, 5, 1, 8, 3, 3, 7])

In [54]:
t[(t > 0) & (t < 5)]

tensor([1, 2, 3, 1, 2, 4, 1, 1, 2, 1, 2, 2, 3, 1, 3, 3])

In [55]:
# boolean index 처리 함수
t.masked_select(t > 0)

tensor([9, 1, 5, 6, 6, 2, 9, 5, 3, 1, 8, 2, 4, 1, 6, 8, 9, 6, 1, 2, 8, 9, 9, 7,
        1, 2, 2, 7, 9, 3, 5, 1, 8, 3, 3, 7])

In [56]:
# 함수로 조회
t.masked_select(t > 0)

tensor([9, 1, 5, 6, 6, 2, 9, 5, 3, 1, 8, 2, 4, 1, 6, 8, 9, 6, 1, 2, 8, 9, 9, 7,
        1, 2, 2, 7, 9, 3, 5, 1, 8, 3, 3, 7])

In [ ]:
# 변경
t[0] = 100
t

tensor([100,  -5, -10,  -3,  -8,  -8,   9,  -4,  -9,  -6,  -3,  -2,  -6,   1,
          5,   6,  -7, -10,   6,   2,   9,   5,  -1,  -6,  -2,  -2,  -1,  -6,
         -5,   3,   1,  -1,  -7,   8, -10,   0,   2,  -1,  -7,  -5, -10, -10,
         -9,  -2,  -6,  -8,  -1,  -4,  -1,   4,   1,  -6,   6,  -1,  -1,  -1,
         -8,  -1,  -2,  -9,  -2,   8,  -6,   9,   6,   1,  -4,   2,   0,   8,
          9,   0, -10,   9,   0,   7,   1,   2,   2,   7,   9,  -1,  -7,  -7,
          3,  -1,   5,  -4,   1,  -2, -10,  -5,  -7,   8,  -8,  -5,   3,   3,
          7,   0])

In [58]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# t[ 0축, 1축 ]
t[1, 2].item()
# t[0, 2].item()

6

In [60]:
t[[1,0], [2,2]]  #(1,2), (0,2)
# t[[첫번째값, 두번째값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

# Reshape

## shape 변경
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > tensor.clone(): tensor를 복제한다.

In [61]:
a=torch.rand(12)
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)


torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [62]:
a

tensor([0.7504, 0.1340, 0.9323, 0.4926, 0.4778, 0.3632, 0.3681, 0.5250, 0.2559,
        0.0349, 0.2424, 0.4005])

In [63]:
a2  # a.reshape*3, 4)

tensor([[0.7504, 0.1340, 0.9323, 0.4926],
        [0.4778, 0.3632, 0.3681, 0.5250],
        [0.2559, 0.0349, 0.2424, 0.4005]])

In [64]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [65]:
a

tensor([0.7504, 0.1340, 0.9323, 0.4926, 0.4778, 0.3632, 0.3681, 0.5250, 0.2559,
        0.0349, 0.2424, 0.4005])

In [66]:
a5  # a.view(3, 4)

tensor([[0.7504, 0.1340, 0.9323, 0.4926],
        [0.4778, 0.3632, 0.3681, 0.5250],
        [0.2559, 0.0349, 0.2424, 0.4005]])

In [67]:
a2  # a.reshape(3,4)

tensor([[0.7504, 0.1340, 0.9323, 0.4926],
        [0.4778, 0.3632, 0.3681, 0.5250],
        [0.2559, 0.0349, 0.2424, 0.4005]])

In [68]:
# a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a)

tensor([ 0.7504, 15.1000,  0.9323,  0.4926,  0.4778,  0.3632,  0.3681,  0.5250,
         0.2559,  0.0349,  0.2424,  0.4005])


In [69]:
a4

tensor([[[ 0.7504, 15.1000],
         [ 0.9323,  0.4926]],

        [[ 0.4778,  0.3632],
         [ 0.3681,  0.5250]],

        [[ 0.2559,  0.0349],
         [ 0.2424,  0.4005]]])

In [71]:
# tensor복사: clone() 메소드
# r = a.clone().reshape(3,4)
r =-- a.reshape(3, 4).clone()
r[0,0] = 100.1
print(a)

tensor([ 0.7504, 15.1000,  0.9323,  0.4926,  0.4778,  0.3632,  0.3681,  0.5250,
         0.2559,  0.0349,  0.2424,  0.4005])


In [72]:
r

tensor([[1.0010e+02, 1.5100e+01, 9.3233e-01, 4.9258e-01],
        [4.7777e-01, 3.6316e-01, 3.6808e-01, 5.2503e-01],
        [2.5591e-01, 3.4897e-02, 2.4245e-01, 4.0050e-01]])

## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)

In [ ]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

a1, a2 = a[None, :], a.unsqueeze(dim=0) # dim=정수만가능
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1)   # a[:, None] # 0축 :, 1축 None, 2번축 지정안함 -> 원래대로 그래서 (2, 1, 2) 가됨.
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:, None], a3.unsqueeze(dim=1)  # unsqueeze(): dim=정수만가능 (한번에 dummy 축은 하나만 추가가능.)
print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [74]:
t = torch.rand(3, 1, 4, 1, 5, 1)
print(t.shape)

r1 = t.squeeze()  #축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 4, 1, 5, 1])
torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5, 1])
torch.Size([3, 4, 5, 1])


## tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0) : 기준축 default 는 0

In [75]:
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3)
print(a)
print(b)
print(c)
print(d)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [76]:
torch.cat([a, b], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [77]:
torch.cat([a, b, c], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [78]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [79]:
torch.cat([a, b, c], axis=1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [80]:
torch.cat([a, b], axis=-1)  # -1: 마지막 axis

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [81]:
a.shape, d.shape
# 합치는 기준축 이외의 축 size는 같아야 한다.
# torch.cat([a, d])  #dim=0, Error  1축 size가 달라서 Error

(torch.Size([2, 5]), torch.Size([3, 3]))

## 값의 위치(index) 변경
- tensor 원소의 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)`  ## 2차원에서 사용
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

In [ ]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)
# X
y = X.transpose(1, 2)
print(y.shape)

z = X.permute(2, 0, 1)
print(z.shape)

# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산지 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [82]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [83]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [84]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [85]:
a.size(), c.size()

(torch.Size([2, 5]), torch.Size([5]))

In [86]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산함수

In [ ]:
## 자연상수 e
torch.e, np.e

In [87]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) # 절대값 
print(torch.sqrt(torch.abs(x))) #  제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x)))
print(torch.log(torch.exp(torch.tensor(1))))  # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)
tensor(1.)


In [88]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=2)) # 소수점 둘째자리 이하에서 반올림
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-4.5166, -1.1892, -1.5052],
        [-0.2561,  1.5963,  1.6596],
        [ 1.3174,  0.8328,  2.6851]])
tensor([[-5., -1., -2.],
        [-0.,  2.,  2.],
        [ 1.,  1.,  3.]])
tensor([[-4.5200, -1.1900, -1.5100],
        [-0.2600,  1.6000,  1.6600],
        [ 1.3200,  0.8300,  2.6900]])
tensor([[-5., -2., -2.],
        [-1.,  1.,  1.],
        [ 1.,  0.,  2.]])
tensor([[-4., -1., -1.],
        [-0.,  2.,  2.],
        [ 2.,  1.,  3.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [89]:
import torch

In [90]:
x = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])

y = torch.FloatTensor([[1, 2],[1, 2],])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [91]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [92]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# 피연산자로 두개의 3차원 tensor를 axis (1, 2)를 기준으로 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape


torch.Size([3, 4, 5])

## torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [ ]:
print(torch.inf > 100000000, torch.inf < 10)
print(-torch.inf < 10, -torch.inf > 10)

True False
True False


In [94]:
print(torch.log(torch.tensor(-1))) # nan (계산결과가 없으므로-없는값-nan 반환)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


## 기술통계함수

In [95]:
X=torch.randn(3,4)
print(X)

tensor([[-2.0602,  0.7522,  0.5141,  1.0058],
        [ 1.3378, -0.3619, -0.0388,  1.0391],
        [-1.6481,  0.6880,  0.5479,  0.7881]])


In [ ]:
print(torch.sum(X))  # default: 전체기준으로 계산. dim=None
print(torch.sum(X, dim=1)) #dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산.
print(torch.sum(X, dim=1, keepdims=True)) # 기술통계함수들을 실행하면 차원이 줄어든다. keepdims=True로 하면 차원유지. 3 x 4 ->  3 x 1 로 만들어줌.

tensor(2.5642)
tensor([0.2120, 1.9763, 0.3759])
tensor([[0.2120],
        [1.9763],
        [0.3759]])


In [ ]:
print(torch.mean(X))
print(torch.mean(X, dim=0))
print(torch.mean(X, dim=0, keepdims=True))  # 차원수를 맞춰서, 3 x 4 ->  1 x 4 로 만들어줌.

tensor(0.2137)
tensor([-0.7902,  0.3594,  0.3411,  0.9444])
tensor([[-0.7902,  0.3594,  0.3411,  0.9444]])


In [101]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))

tensor(1.0724)
tensor(1.1501)
tensor([3.4385, 0.3912, 0.1085, 0.0186])


In [102]:
# tensor.메소드() 
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[0.2120],
        [1.9763],
        [0.3759]])
tensor([[0.0530],
        [0.4941],
        [0.0940]])
tensor(1.0724)


In [103]:
X

tensor([[-2.0602,  0.7522,  0.5141,  1.0058],
        [ 1.3378, -0.3619, -0.0388,  1.0391],
        [-1.6481,  0.6880,  0.5479,  0.7881]])

In [ ]:
print(torch.max(X)) # 전체 기준 max값 계산.
print(torch.max(X, dim=0))  # 축을 지정하면 return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
print(torch.max(X, dim=1))
print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")
print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
print(torch.max(X, dim=1, keepdims=True))

tensor(1.3378)
torch.return_types.max(
values=tensor([1.3378, 0.7522, 0.5479, 1.0391]),
indices=tensor([1, 0, 2, 1]))
torch.return_types.max(
values=tensor([1.0058, 1.3378, 0.7881]),
indices=tensor([3, 0, 3]))
tensor([1.0058, 1.3378, 0.7881]) || tensor([3, 0, 3])
torch.return_types.max(
values=tensor([[1.3378, 0.7522, 0.5479, 1.0391]]),
indices=tensor([[1, 0, 2, 1]]))
torch.return_types.max(
values=tensor([[1.0058],
        [1.3378],
        [0.7881]]),
indices=tensor([[3],
        [0],
        [3]]))


In [117]:
print(torch.min(X))
print(torch.min(X, dim=0)) # return_types.min 타입객체로 반환. min값과 min값의 index를 묶어서 반환
print(torch.min(X, dim=1))

print(torch.argmax(X))
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor(-2.0602)
torch.return_types.min(
values=tensor([-2.0602, -0.3619, -0.0388,  0.7881]),
indices=tensor([0, 1, 1, 2]))
torch.return_types.min(
values=tensor([-2.0602, -0.3619, -1.6481]),
indices=tensor([0, 1, 0]))
tensor(4)
tensor([1, 0, 2, 1])
tensor([3, 0, 3])


In [118]:
a = torch.max(X, dim=0)
print(a.values)
print(a.indices)

tensor([1.3378, 0.7522, 0.5479, 1.0391])
tensor([1, 0, 2, 1])


# autograd(자동미분)
- 자동 미분을 이용해 gradient(미분계수)를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면(gradient 계산 대상 변수) `requires_grad=True` 로 설정되 있어야 한다. (default: False)
    

In [133]:
import torch

In [ ]:
# x 가 변하면 y 는 얼마나 변할까? x 지점에서의 변화율(순간변화율) 계산.

In [134]:
x = torch.tensor([1.0], requires_grad=True)  # gradient 구할 대상변수에 requires_grad=True

In [135]:
print(x.grad)
print(x.data)  # tensor 에 저장한 값들은 data속성에 저장.

None
tensor([1.])


In [136]:
y = x ** 2   # X의 도함수를 계산.  => X.grad_fn 에 저장.

In [137]:
y

tensor([1.], grad_fn=<PowBackward0>)

In [138]:
print(y.grad_fn)

In [130]:
# gradient 를 계산(x 변화에 대한 y의 변화율)
y.backward()  # X의 gradient값을 계산해서 X 의 grad속성에 저장.

In [131]:
x.grad

tensor([2.])

In [ ]:
x = torch.tensor([2.0], requires_grad=True)
# y = x**2   # 도함수를 만듬.
# y = x + 3      # 더한 값의 출력값. AddBackward0 at 0x153387462f0>
y = x - 3        # 뺀 값의 출력값. SubBackward0 at 0x153385f22f0>)
y.backward()  # x 의 gradient를 계산. 그 gradient 값을 x 에 저장

In [143]:
x.data, x.grad, y.grad_fn

(tensor([2.]), tensor([1.]), <SubBackward0 at 0x153385f22f0>)

In [146]:
input_data = torch.tensor([03.2])
weight = torch.tensor([0.2], requires_grad=True)
y_pred = input_data * weight
y_pred.backward()

In [148]:
print(y_pred.grad_fn)
print(weight.grad)

tensor([3.2000])


In [149]:
weight = weight.data = weight.grad * 0.01
weight

tensor([0.0320])

In [151]:
## 합성함수 미분
a = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([2.0], requires_grad=True)

y = a ** 2
z = y * b   # z = (a**2) * b

In [152]:
z.backward()

In [153]:
print(b.data, b.grad)

tensor([2.]) tensor([1.])


In [154]:
print(a.data, a.grad)

tensor([1.]) tensor([4.])


In [157]:
#편미분
a = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([2.0], requires_grad=True)

y = a * b  # a 에 대한 y의 변화뮬( b는 상수취급), b에 대한 y의 변화율(a는 상수 취급)
# dy/da, dy/db

In [158]:
y.grad_fn

In [159]:
y.backward()

In [ ]:
a.grad, b.grad

(tensor([2.]), tensor([1.]))

## torch.no_grad() 
- no_grad() 구문에서 연산을 할 경우 requires_grad=True로 설정되었다 하더라도 gradient를 update하지 않는다.
- 딥러닝 모델 학습이 끝나고 평가할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [161]:
x = torch.tensor([1.0], requires_grad=True)
y = x * 2
print('결과:', y.data)
y.grad_fn

결과: tensor([2.])


In [ ]:
x = torch.tensor([1.0], requires_grad=True)

with torch.no_grad():   # with문 안에서 requires_grad=True인 변수를 이용해 계산해도 grad_fn을 만들지 않는다.
    y = x ** 2
    print(y.grad_fn, y)

None tensor([1.])


In [166]:
y = x ** 2
print(y.grad_fn)

## gradient 값 초기화

In [ ]:
x = torch.tensor(1.0, requires_grad=True)
print(x.grad)
y = x ** 2  # x ** 2 -> 2*x
y.backward()
print(x.grad)   # tensor의 grad에 값이 이미 있는 경우 계속 더해진다. => grad 값을 초기화(0, None으로 변경.)

None
tensor(2.)


In [170]:
# 새로운 계산
x.grad = None
z = x **3  # grad_fn: 3*x
z.backward()
print(x.grad)  # 값이 계속 + 누적됨.

tensor(3.)


In [171]:
x.grad = None  # 초기화 -> 새작업
#새작업
z = x **3  # grad_fn: 3*x
z.backward()
print(x.grad)  # 값이 계속 + 누적됨.

tensor(3.)
